import SwiftUI
import ComposeApp

/// Thin SwiftUI wrapper that embeds the Compose Multiplatform UI.
///
/// The entire app UI (navigation, chat, documents, settings) lives in the
/// KMP `composeApp` module — Swift just hosts it here.
struct ContentView: View {
    var body: some View {
        ComposeView()
            .ignoresSafeArea(.keyboard)  // Compose handles IME insets itself
    }
}

/// UIViewControllerRepresentable that creates the Compose root controller.
private struct ComposeView: UIViewControllerRepresentable {

    func makeUIViewController(context: Context) -> UIViewController {
        // MainViewControllerKt.MainViewController() is generated by the KMP
        // Compose framework from the @Composable entry point in commonMain.
        MainViewControllerKt.MainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}
